/**
 * Plugin writers for agents that expose only IN-PROCESS plugin APIs (no
 * external-command hooks): OpenCode (JS plugin) and pi (TS extension). Instead of
 * a config that runs notify.sh, we generate a small plugin file that, on
 * lifecycle events, POSTs to the daemon hook server itself — port + secret baked
 * in at install time (like notify.sh), VERNE_TAB_ID / VERNE_AGENT_ID read from
 * the agent process env. The plugin no-ops for non-Verne sessions (no
 * VERNE_TAB_ID) and is fire-and-forget so it can never break the agent.
 *
 * The plugins emit Verne's CANONICAL event names (UserPromptSubmit / PreToolUse /
 * PostToolUse / Stop / PermissionRequest) so the daemon's existing hook_to_state
 * maps them with no changes.
 */

import { mkdirSync, writeFileSync, existsSync, rmSync, renameSync } from "node:fs";
import { join, dirname } from "node:path";
import { homedir } from "node:os";

function writeFileAtomic(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = path + ".tmp";
  writeFileSync(tmp, content, { encoding: "utf8" });
  renameSync(tmp, path);
}

// ── OpenCode ──────────────────────────────────────────────────────────────────
// ~/.config/opencode/plugin/verne.js — plain JS (Bun runtime, global fetch). The
// factory returns a hooks object; unknown keys are ignored, so a drifted event
// name simply won't fire (no crash).

// opencode renamed `plugin/` → `plugins/`; write both so old + new versions
// load it (double-loading is harmless — duplicate posts map to the same state).
const OPENCODE_PLUGIN_PATHS = [
  join(homedir(), ".config", "opencode", "plugin", "verne.js"),
  join(homedir(), ".config", "opencode", "plugins", "verne.js"),
];

function opencodePluginSource(port: number, secret: string): string {
  return `// AUTO-GENERATED by Verne. Forwards OpenCode lifecycle events to Verne's hook
// server. No-ops outside a Verne-spawned session. Safe to delete.
const PORT = ${port};
const SECRET = ${JSON.stringify(secret)};
const TAB = process.env.VERNE_TAB_ID || "";
const AGENT = process.env.VERNE_AGENT_ID || "";
const SOURCE = "plugin:opencode:" + Date.now() + ":" + Math.random();
let seq = 0;

function post(event, payload) {
  if (!TAB) return; // not a Verne session
  try {
    fetch("http://127.0.0.1:" + PORT + "/hook", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Verne-Event": event,
        "X-Verne-Agent-Id": AGENT,
        "X-Verne-Tab-Id": TAB,
        "X-Verne-Agent-Type": "opencode",
        "X-Verne-Source": SOURCE,
        "X-Verne-Seq": String(++seq),
        "X-Verne-Daemon-Secret": SECRET,
      },
      body: JSON.stringify(payload || {}),
    }).catch(function () {});
  } catch (e) {}
}

export const VernePlugin = async function () {
  return {
    "chat.message": async function (_input, output) {
      post("UserPromptSubmit", { message: output && output.message });
    },
    "tool.execute.before": async function (input, output) {
      post("PreToolUse", { tool_name: input && input.tool, tool_input: output && output.args });
    },
    "tool.execute.after": async function (input) {
      post("PostToolUse", { tool_name: input && input.tool });
    },
    // Catch-all bus — the reliable path for session idle + permission prompts.
    event: async function (e) {
      const ev = e && e.event;
      if (!ev || !ev.type) return;
      if (ev.type === "session.idle") post("Stop", {});
      else if (ev.type === "permission.asked" || ev.type === "permission.updated")
        post("PermissionRequest", { approval_required: true });
    },
  };
};
`;
}

export function ensurePluginForOpencode(port: number, secret: string): void {
  for (const p of OPENCODE_PLUGIN_PATHS) writeFileAtomic(p, opencodePluginSource(port, secret));
}

export function removePluginForOpencode(): void {
  for (const p of OPENCODE_PLUGIN_PATHS) if (existsSync(p)) rmSync(p);
}

// ── pi ────────────────────────────────────────────────────────────────────────
// ~/.pi/agent/extensions/verne.ts — TS (loaded via jiti; types are erased). No
// package import so a differing install path can't break loading; `pi.on` with an
// unknown event just never fires.

const PI_EXTENSION_PATH = join(homedir(), ".pi", "agent", "extensions", "verne.ts");

function piExtensionSource(port: number, secret: string): string {
  return `// AUTO-GENERATED by Verne. Forwards pi lifecycle events to Verne's hook server.
// No-ops outside a Verne-spawned session. Safe to delete.
const PORT = ${port};
const SECRET = ${JSON.stringify(secret)};
const TAB = process.env.VERNE_TAB_ID || "";
const AGENT = process.env.VERNE_AGENT_ID || "";
const SOURCE = "plugin:pi:" + Date.now() + ":" + Math.random();
let seq = 0;

function post(event: string, payload: unknown): void {
  if (!TAB) return; // not a Verne session
  try {
    void fetch("http://127.0.0.1:" + PORT + "/hook", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Verne-Event": event,
        "X-Verne-Agent-Id": AGENT,
        "X-Verne-Tab-Id": TAB,
        "X-Verne-Agent-Type": "pi",
        "X-Verne-Source": SOURCE,
        "X-Verne-Seq": String(++seq),
        "X-Verne-Daemon-Secret": SECRET,
      },
      body: JSON.stringify(payload || {}),
    }).catch(function () {});
  } catch (e) {}
}

export default function (pi: { on: (event: string, handler: (event: unknown) => void) => void }) {
  pi.on("session_start", function (e) { post("SessionStart", e); });
  pi.on("agent_start", function (e) { post("UserPromptSubmit", e); });
  pi.on("input", function (e) { post("UserPromptSubmit", e); });
  pi.on("tool_call", function (e) { post("PreToolUse", e); });
  pi.on("tool_result", function (e) { post("PostToolUse", e); });
  pi.on("agent_end", function (e) { post("Stop", e); });
}
`;
}

export function ensurePluginForPi(port: number, secret: string): void {
  writeFileAtomic(PI_EXTENSION_PATH, piExtensionSource(port, secret));
}

export function removePluginForPi(): void {
  if (existsSync(PI_EXTENSION_PATH)) rmSync(PI_EXTENSION_PATH);
}
