<script setup lang="ts">
import { ref, watch, onMounted, computed } from "vue";
import { useTheme } from "@/composables/useTheme";
import { tokenizeCodeBlockToHtml } from "@/lib/textmate";

const { themeVersion, getActiveThemeSpec } = useTheme();

// Mini editor frame containing a unified-diff hunk. One panel demonstrates:
//   - header chrome (border, card surface, muted text)
//   - syntax highlighting across keywords, strings, types, numbers, comments
//   - line numbers (gutter color via --muted-foreground)
//   - diff-line backgrounds from editor."diffEditor.{removed,inserted}LineBackground"
type Op = "ctx" | "del" | "add";
type SourceLine = { op: Op; ln: number | null; text: string };

const SOURCE: SourceLine[] = [
  { op: "ctx", ln:  1, text: `// Theme tokens currently in use` },
  { op: "ctx", ln:  2, text: `type Surface = "card" | "sidebar";` },
  { op: "ctx", ln:  3, text: `` },
  { op: "ctx", ln:  4, text: `const config: Theme = {` },
  { op: "del", ln:  5, text: `  surface: "sidebar",` },
  { op: "add", ln:  5, text: `  surface: "sidebar-elevated",` },
  { op: "ctx", ln:  6, text: `  accent: "#0ea5e9",` },
  { op: "ctx", ln:  7, text: `  contrast: 68,` },
  { op: "ctx", ln:  8, text: `};` },
  { op: "ctx", ln:  9, text: `` },
  { op: "ctx", ln: 10, text: `export function apply(t: Theme): void {` },
  { op: "ctx", ln: 11, text: `  document.documentElement` },
  { op: "ctx", ln: 12, text: `    .setAttribute("data-theme", t.name);` },
  { op: "ctx", ln: 13, text: `}` },
];

const rendered = ref<{ op: Op; ln: number | null; html: string }[]>([]);

async function refresh() {
  // Tokenize as one block so multi-line scopes (block comments, template
  // literals) stay correct. Tokens are regex-based, so the adjacent del/add
  // pair doesn't confuse the highlighter.
  const html = await tokenizeCodeBlockToHtml(
    SOURCE.map((l) => l.text).join("\n"),
    "typescript",
  );
  const htmlLines = html.split("\n");
  rendered.value = SOURCE.map((src, i) => ({
    op: src.op,
    ln: src.ln,
    html: htmlLines[i] || "&nbsp;",
  }));
}

onMounted(refresh);
watch(themeVersion, refresh);

const diff = computed(() => {
  const e = getActiveThemeSpec().editor;
  return {
    del: e["diffEditor.removedLineBackground"] ?? "#f0637215",
    add: e["diffEditor.insertedLineBackground"] ?? "#8cc46f15",
    delGutter: e["editorOverviewRuler.deletedForeground"] ?? "#dc2626",
    addGutter: e["editorOverviewRuler.addedForeground"] ?? "#16a34a",
  };
});

function lineBg(op: Op) {
  return op === "del" ? diff.value.del : op === "add" ? diff.value.add : "";
}
function gutterColor(op: Op) {
  return op === "del" ? diff.value.delGutter : op === "add" ? diff.value.addGutter : "";
}
function sign(op: Op) {
  return op === "del" ? "−" : op === "add" ? "+" : "";
}
</script>

<template>
  <div
    class="rounded-lg border border-border overflow-hidden font-mono text-xs leading-relaxed"
    :style="{ backgroundColor: 'var(--editor-bg)' }"
  >
    <div class="px-3 py-1.5 border-b border-border bg-card">
      <span class="text-[11px] text-muted-foreground tracking-wide">themePreview.ts</span>
    </div>

    <div class="overflow-x-auto py-2">
      <div
        v-for="(line, i) in rendered"
        :key="i"
        class="flex relative"
        :style="{ backgroundColor: lineBg(line.op) }"
      >
        <span
          v-if="line.op !== 'ctx'"
          class="absolute left-0 top-0 bottom-0 w-0.5"
          :style="{ backgroundColor: gutterColor(line.op) }"
        />
        <span class="w-8 shrink-0 pr-2 text-right text-muted-foreground select-none tabular-nums">{{ line.ln ?? "" }}</span>
        <span
          class="w-4 shrink-0 text-center select-none"
          :style="{ color: gutterColor(line.op) }"
        >{{ sign(line.op) }}</span>
        <!-- eslint-disable vue/no-v-html -- generated by tokenizeCodeBlockToHtml, which escapes token text before wrapping spans. -->
        <span class="flex-1 pr-3 whitespace-pre" v-html="line.html" />
        <!-- eslint-enable vue/no-v-html -->
      </div>
    </div>
  </div>
</template>
